### PR TITLE
dedicated oh fucking boy copypasta

### PR DESCRIPTION
**Pull request by binex-dsk**

### CODE REVIEW

**Comment by BowDown097** [comment]
not based

**Comment by binex-dsk** [comment]
what about kizu copypasta :Swirl:

**Comment by LennyMcLennington** [comment]
what about BIG BLACK NIGGER

**Comment by binex-dsk** [comment]
u

**Comment by binex-dsk** [comment]
I’m leaving the server. I’m sick and tired of the same people saying the same shit everyday. Its cringe. All you fucking losers do is sit here and simp each other left and right. I’m sick of it. Don’t even get me started on the staff. You nazi fucks sit there and think youre better than everyone else muting left and right whenever things start getting interesting. Not even a fucking warning, its sad. freaks. All of you should fucking neck 7 times over.

**Pull request closed without merging**
